### ISSUE TITLE
python3 type eror for getAPinfo()

### ISSUE THREAD

**Issue by pandazc31** [jvillagomez/rssi_module#14]
i try to follow your tutorial as per bellow picture 
![Q1](https://user-images.githubusercontent.com/85219807/120444365-c237da00-c3b1-11eb-8c6b-a4a72f105fec.PNG)

but i got some error like this picture
![Q2](https://user-images.githubusercontent.com/85219807/120444431-cebc3280-c3b1-11eb-8555-4d1a96af5b14.PNG)
 
there is any solution ?

**Comment by pandazc31** [comment]
in this case it was clear ,i was using python 2 it's work

**Comment by vladivanovic** [comment]
@pandazc31 looks like you need to go to the __init__.py file and add a line to line 68 to convert the output to utf-8 - the exact code is here: https://github.com/jvillagomez/rssi_module/issues/11

**Comment by vladivanovic** [comment]
ok maybe that didn't fix it for me either... looks like some digging needed. 

Python 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rssi
>>> interface = 'wlan0'
>>> rssi_scanner = rssi.RSSI_Scan(interface)
>>> ap_info = rssi_scanner.getAPinfo(sudo=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vlad/.local/lib/python3.8/site-packages/rssi/__init__.py", line 305, in getAPinfo
    all_access_points = self.formatCells(raw_scan_output)
  File "/home/vlad/.local/lib/python3.8/site-packages/rssi/__init__.py", line 203, in formatCells
    raw_cells = raw_cell_string.split('Cell') # Divide raw string into raw cells.
TypeError: a bytes-like object is required, not 'str'

**Comment by vladivanovic** [comment]
Just checking now, the Github version of RSSI vs the pip3 version is dramatically different, going to try and see what happens if I use the Github version.

**Comment by nabsha** [comment]
Getting the same error on raspberry pi, any plans to resolve the issues and update pip please?

![image](https://user-images.githubusercontent.com/2717604/131128476-8c5aa868-0b62-4745-bc4d-100ab09a8d78.png)

**Comment by ksirirux** [comment]
$ pip show rssi  #to find location library
![2022-03-12_100609](https://user-images.githubusercontent.com/30040135/158001456-56c24e10-5a03-436a-970c-ea2ae2c7626a.jpg)
go to library 
![2022-03-12_100754](https://user-images.githubusercontent.com/30040135/158001464-420090de-773d-4b18-ba29-ec03dff8a9ac.jpg)
add  raw_output= raw_output.decode("utf-8")
![2022-03-12_100724](https://user-images.githubusercontent.com/30040135/158001487-ec32402c-459b-4b2a-9435-78811a98e73b.jpg)


It work !!
