### ISSUE TITLE
getAPinfo() broken in Python3

### ISSUE THREAD

**Issue by mdrisser** [jvillagomez/rssi_module#6]
When attempting to run this under Python3, I get the following when trying to run getAPinfo()

``>>> apinfo=scanner.getAPinfo(networks=ssids, sudo=True)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/rssi/__init__.py", line 305, in getAPinfo
    all_access_points = self.formatCells(raw_scan_output)
  File "/usr/local/lib/python3.7/dist-packages/rssi/__init__.py", line 203, in formatCells
    raw_cells = raw_cell_string.split('Cell') # Divide raw string into raw cells.
TypeError: a bytes-like object is required, not 'str'

**Comment by abitencourtjunior** [comment]
Hi @mdrisser , see link: https://github.com/jvillagomez/rssi_module/issues/1

**Comment by jvillagomez** [comment]
Hi @mdrisser , I apologize for the previous lack of support. The project is now updated to run as expected on python3. Within the next 24 hours I will update the pip package as well.

I will now be actively supporting this module, and will be adding a few new features within the next two weeks. Have a look at the README if you have any questions on the upcoming features.

**Comment by mdrisser** [comment]
pip package is still broken, running it under a fresh OS install and a fresh pip install I receive the same error.

**Comment by vladivanovic** [comment]
June 2021 here and I'm still getting the same error as above as well. Will manually update the file I have with what looks to be the fix :)
