### ISSUE TITLE
Singular matrix With your code

### ISSUE THREAD

**Issue by tejastank** [jvillagomez/rssi_module#8]
Traceback (most recent call last):
  File "RSSI_Localizer.py", line 269, in <module>
    p = o.getNodePosition([4, 2 , 3])
  File "RSSI_Localizer.py", line 235, in getNodePosition
    position = self.computePosition(a, b)
  File "RSSI_Localizer.py", line 210, in computePosition
    inv_at_a = numpy.linalg.inv(at_a)
  File "/usr/lib/python3/dist-packages/numpy/linalg/linalg.py", line 513, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/usr/lib/python3/dist-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix

Default your code when try to run 

accessPoints = [{
             'signalAttenuation': 3, 
             'location': {
                 'y': 1, 
                 'x': 1
             }, 
             'reference': {
                 'distance': 4, 
                 'signal': -50
             }, 
             'name': 'dd-wrt'
         },
         {
             'signalAttenuation': 4, 
             'location': {
                 'y': 1, 
                 'x': 7
             }, 
             'reference': {
                 'distance': 3, 
                 'signal': -41
             }, 
             'name': 'ucrwpa'
         }]

print(accessPoints)
o = RSSI_Localizer(accessPoints)
p = o.getNodePosition([4, 2 , 3])

**Comment by jvillagomez** [comment]
Hi @tejastank, it looks like you're trying to run the package using the data listed in the example. Unless you are in a location where the networks **ucrwpa** and **dd-wrt** are within range, this will not work in your case.

In any case, that error isnt descriptive at all, so I will definitely fix this so the error is more descriptive (or at least wont throw this error).

**Comment by jvillagomez** [comment]
Hi @tejastank., allow me to investigate what is going on here. Will report shortly.
